config/routes.rb
SeekRefer::Application.routes.draw do
  
  get 'autocomplete_company_name' => 'application#autocomplete_company_name'
  
  get "region_page/index"
  devise_for :users
  resources :companies
  resources :users
  resources :job_posts do
    get :autocomplete_position_name, :on => :collection
    get :autocomplete_company_name, :on => :collection
  end
  resources :follow_rules
  root 'homes#index'
  get 'homes' => 'homes#index'
  
  match '/signin',  to: 'devise/sessions#new',    via: 'get'
  
  get 'connects/send_request/:id' => 'connects#send_request'
  get 'connects/accept_request' => 'connects#accept_request'
  get 'connects/ignore_request' => 'connects#ignore_request'
  get 'connects/disconnect/:id' => 'connects#disconnect'
  post 'users/create' => 'users#create'
  get 'connects' => 'connects#index'

  
  get 'refer_requests/send_request' => 'refer_requests#send_request'
  post 'refer_requests/recv_request' => 'refer_requests#recv_request'
  get 'refer_request/view_profile' => 'refer_requests#view_profile'
  get 'refer_request/ignore_request' => 'refer_requests#ignore_request'
  get 'refer_request/upload_resume' => 'refer_requests#upload_resume'
  post 'refer_request/save_resume' => 'refer_requests#save_resume'
  post 'refer_request/refuse_request' => 'refer_requests#refuse_request'
  
  get 'refer_cases/show_referrer' => 'refer_cases#show_referrer'
  get 'refer_cases/show_referrer_old' => 'refer_cases#show_referrer_old'
  get 'refer_cases/show_referral' => 'refer_cases#show_referral'
  get 'refer_cases/show_referral_old' => 'refer_cases#show_referral_old'
  get 'refer_cases/create' => 'refer_cases#create'
  get 'refer_cases/edit' => 'refer_cases#edit'
  patch 'refer_cases/destroy' => 'refer_cases#destroy'
  patch 'refer_cases/update' => 'refer_cases#update'
  get 'refer_cases/feedback' => 'refer_cases#feedback'
  
  post 'refer_posts/create' => 'refer_posts#create'
  
  get 'linkedin/get_token' => 'linkedin#get_token'
  get 'linkedin/accept' => 'linkedin#accept'
  get 'linkedin/get_companies' => 'linkedin#get_companies'
  get 'linkedin/get_company' => 'linkedin#get_company'
  get 'linkedin/new' => 'linkedin#new'
  post 'linkedin/create' => 'linkedin#create'
  get 'linkedin/get_jobs_by_company' => 'linkedin#get_jobs_by_company'
 
 
  
 

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Model Associations 
  has_many :connects, ->{ where accepted: true},  foreign_key: "from_id"
  has_many :connect_users, :source => :to, class_name: "User", :through => :connects, uniq: true
  has_many :referrer_cases, class_name: "ReferCase", foreign_key: "referrer_id" 
  has_many :referral_cases, class_name: "ReferCase", foreign_key: "referral_id" 
  belongs_to :company
  belongs_to :location
  belongs_to :hometown, class_name: "ChinaCity"
  belongs_to :china_school1, class_name: "ChinaCollege", foreign_key: "china_school1_id"
  belongs_to :china_school2, class_name: "ChinaCollege", foreign_key: "china_school2_id"
  belongs_to :us_school1, class_name: "UsCollege", foreign_key: "us_school1_id"
  belongs_to :us_school2, class_name: "UsCollege", foreign_key: "us_school2_id"
  
  # before save user to database, check company if exist in company database
  before_save :verify_company
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #Paperclip
  has_attached_file :avatar, :styles => { :medium => "150x150#", 
                                          :small => "100x100#", 
                                          :thumb => "50x50#" }, 
                              :default_url => "/images/users/defaultAvatar_:style.png"
                              
                              
  def verify_company
    if self.company_id.nil? && !self.company_name.nil?
      #create new company item 
      company = Company.new(name:self.company_name, is_active:true)
      company.save
      self.company_id = company.id
      
      Thread.new{ update_company(company.id, self.company_name) }
      
    elsif !self.company_id.nil?
      #set is_active field for this company, which means some users belongs to this company
      company = Company.find(self.company_id)
      if company.is_active == false
        company.is_active = true
        company.save
      end
      
    end
    
    def update_company(company_id, company_name)
      
      if LinkedinController.new.update_company(company_id, company_name)
        company = Company.find(company_id)
        company.is_verified = true
        company.save
      else
        # fail to supplement info for new company
      end 
    end
    
  end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin, except: [:show, :connect]
  
  def require_admin
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end
  
  def new
    @user = User.new
  end
  
  #sign up
  def signup  
    @user = User.new
  end
  
  def index
    @users = User.all
  end 
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Add User: " + params[:user][:name] + " to DB!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to companies_path
  end
   
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :company_id, :company_name, :dept, :position,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>更新个人资料</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name ,"用户名"%>
      <%= f.text_field :name %>
      
      <%= f.label :company ,"公司"%>
      <%= f.text_field :company %>
      
      <%= f.label :dept, "部门" %>
      <%= f.text_field :dept %>
      
      <%= f.label :position, "职位"%>
      <%= f.text_field :position %>

      <%= f.label :email ,"邮箱"%>
      <%= f.text_field :email %>

      <%= f.label :password , "密码"%>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "更新", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<%= link_to '添加用户', new_user_path, class: "btn btn-primary" %><br /><br />

<table class="table table-hover">
  <tr>
    <th>用户名</th>
    <th>公司</th>
    <th>部门</th>
    <th>职位</th>
    <th>邮箱</th>
    <th></th>
    <th></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
    	  <td><%= link_to user.name, user_path(user) %></td>
      <td><%= user.company.name %></td>
      <td><%= user.dept %></td>
      <td><%= user.position %></td>
      <td><%= user.email %></td>
      <td><%= link_to '修改', edit_user_path(user)%></td>
 	  <td><%= link_to '删除', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for :user, url:users_create_path do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :name, "用户名"%>
      <%= f.text_field :name, :autofocus => true %>

      <%= f.label :email , "邮箱"%>
      <%= f.text_field :email %>

  	  <%= f.label :password , "密码"%>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation %>
      
 	  <%= f.label :company_id , "公司"%>
      <%= f.autocomplete_field :company_name, autocomplete_company_name_path, :id_element=>"#user_company_id", :update_elements => {:name => "#user_company"} %>
      <%= f.hidden_field :company_id %>
      
      <%= f.label :dept, "部门" %>
      <%= f.text_field :dept %>
      
      <%= f.label :position , "职位"%>
      <%= f.text_field :position %>

      <%= f.submit "创建", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p>
	<%= image_tag @user.avatar.url(:small) %>
</p>

<p>
  <strong>用户名</strong>
  <%= @user.name %>
</p>

<p>
  <strong>地区</strong>
  <%= @user.location.name %>
</p>
 
<p>
  <strong>公司</strong>
  <%= @user.company.name %>
</p>

<p>
  <strong>部门</strong>
  <%= @user.dept %>
</p>

<p>
  <strong>职位</strong>
  <%= @user.position %>
</p>

<p>
  <strong>邮箱</strong>
  <%= @user.email %>
</p>

<p>
  <strong>家乡</strong>
  <%= @user.hometown.province %>
</p>

<p>
  <strong>国内毕业院校</strong>
  <%= @user.china_school1.name %>
</p>

<p>
  <strong>海外毕业院校</strong>
  <%= @user.us_school1.name %>
</p>

<%= link_to '更新', edit_user_registration_path %>

app/views/users/signup.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, url: users_path do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :name, "User Name"%>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.label :company %>
      <%= f.text_field :company %>
      
      <%= f.label :dept, "Department" %>
      <%= f.text_field :dept %>
      
      <%= f.label :position %>
      <%= f.text_field :position %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>