config/routes.rb
SeekRefer::Application.routes.draw do
  
  get 'autocomplete_company_name' => 'application#autocomplete_company_name'
  
  get "region_page/index"
  devise_for :users
  resources :companies
  resources :users
  resources :job_posts do
    get :autocomplete_position_name, :on => :collection
    get :autocomplete_company_name, :on => :collection
  end
  resources :follow_rules
  root 'homes#index'
  get 'homes' => 'homes#index'
  
  match '/signin',  to: 'devise/sessions#new',    via: 'get'
  
  get 'connects/send_request/:id' => 'connects#send_request'
  get 'connects/accept_request' => 'connects#accept_request'
  get 'connects/ignore_request' => 'connects#ignore_request'
  get 'connects/disconnect/:id' => 'connects#disconnect'
  post 'users/create' => 'users#create'
  get 'connects' => 'connects#index'

  
  get 'refer_requests/send_request' => 'refer_requests#send_request'
  post 'refer_requests/recv_request' => 'refer_requests#recv_request'
  get 'refer_request/view_profile' => 'refer_requests#view_profile'
  get 'refer_request/ignore_request' => 'refer_requests#ignore_request'
  get 'refer_request/upload_resume' => 'refer_requests#upload_resume'
  post 'refer_request/save_resume' => 'refer_requests#save_resume'
  post 'refer_request/refuse_request' => 'refer_requests#refuse_request'
  
  get 'refer_cases/show_referrer' => 'refer_cases#show_referrer'
  get 'refer_cases/show_referrer_old' => 'refer_cases#show_referrer_old'
  get 'refer_cases/show_referral' => 'refer_cases#show_referral'
  get 'refer_cases/show_referral_old' => 'refer_cases#show_referral_old'
  get 'refer_cases/create' => 'refer_cases#create'
  get 'refer_cases/edit' => 'refer_cases#edit'
  patch 'refer_cases/destroy' => 'refer_cases#destroy'
  patch 'refer_cases/update' => 'refer_cases#update'
  get 'refer_cases/feedback' => 'refer_cases#feedback'
  
  post 'refer_posts/create' => 'refer_posts#create'
  
  get 'linkedin/get_token' => 'linkedin#get_token'
  get 'linkedin/accept' => 'linkedin#accept'
  get 'linkedin/get_companies' => 'linkedin#get_companies'
  get 'linkedin/get_company' => 'linkedin#get_company'
  get 'linkedin/new' => 'linkedin#new'
  post 'linkedin/create' => 'linkedin#create'
  get 'linkedin/get_jobs_by_company' => 'linkedin#get_jobs_by_company'
 
 
  
 

  

end

app/models/china_city.rb
class ChinaCity < ActiveRecord::Base
  has_many :users, foreign_key: "hometown_id"
end

app/models/china_college.rb
class ChinaCollege < ActiveRecord::Base
  has_many :users1, class_name: "User", foreign_key: "china_school1_id"
  has_many :users2, class_name: "User", foreign_key: "china_school2_id" 
end

app/models/company.rb
class Company < ActiveRecord::Base
  require "open-uri"
  
  #Association
  has_many :users
  has_many :locations, :through => :users
  belongs_to :industry
  
  #Paperclip
  has_attached_file :logo, :styles => { :medium => "300x300#", 
                                          :small => "120x120#", 
                                          :thumb => "60x60#" }, 
                              :default_url => "/images/companies/defaultLogo_:style.jpg"

  def logo_from_url(url)
    self.logo = URI.parse(url)
  end
end

app/models/connect.rb
class Connect < ActiveRecord::Base
  belongs_to :from, :class_name => "User", :foreign_key => "from_id"
  belongs_to :to, :class_name => "User", :foreign_key => "to_id"
end

app/models/connect_request.rb
class ConnectRequest < ActiveRecord::Base
  belongs_to :from, :class_name => "User", :foreign_key => "from_id"
  belongs_to :to, :class_name => "User", :foreign_key => "to_id"
end

app/models/follow_rule.rb
class FollowRule < ActiveRecord::Base
  belongs_to :company
  belongs_to :location
  belongs_to :industry
end

app/models/industry.rb
class Industry < ActiveRecord::Base
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  belongs_to :industry
  belongs_to :company
  belongs_to :location
  belongs_to :position
  belongs_to :poster, class_name: "User"
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
  has_many :companies, :through => :users, :uniq => true 
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/refer_case.rb
class ReferCase < ActiveRecord::Base
  belongs_to :referrer, :class_name => "User", :foreign_key => "referrer_id"
  belongs_to :referral, :class_name => "User", :foreign_key => "referral_id"
  has_many :refer_posts
end

app/models/refer_post.rb
class ReferPost < ActiveRecord::Base
  belongs_to :refer_case
  belongs_to :user
end

app/models/refer_request.rb
class ReferRequest < ActiveRecord::Base
  belongs_to :from, :class_name => "User", :foreign_key => "from_id"
  belongs_to :to, :class_name => "User", :foreign_key => "to_id"
end

app/models/us_college.rb
class UsCollege < ActiveRecord::Base
  has_many :users1, class_name: "User", foreign_key: "us_school1_id"
  has_many :users2, class_name: "User", foreign_key: "us_school2_id" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Model Associations 
  has_many :connects, ->{ where accepted: true},  foreign_key: "from_id"
  has_many :connect_users, :source => :to, class_name: "User", :through => :connects, uniq: true
  has_many :referrer_cases, class_name: "ReferCase", foreign_key: "referrer_id" 
  has_many :referral_cases, class_name: "ReferCase", foreign_key: "referral_id" 
  belongs_to :company
  belongs_to :location
  belongs_to :hometown, class_name: "ChinaCity"
  belongs_to :china_school1, class_name: "ChinaCollege", foreign_key: "china_school1_id"
  belongs_to :china_school2, class_name: "ChinaCollege", foreign_key: "china_school2_id"
  belongs_to :us_school1, class_name: "UsCollege", foreign_key: "us_school1_id"
  belongs_to :us_school2, class_name: "UsCollege", foreign_key: "us_school2_id"
  
  # before save user to database, check company if exist in company database
  before_save :verify_company
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #Paperclip
  has_attached_file :avatar, :styles => { :medium => "150x150#", 
                                          :small => "100x100#", 
                                          :thumb => "50x50#" }, 
                              :default_url => "/images/users/defaultAvatar_:style.png"
                              
                              
  def verify_company
    if self.company_id.nil? && !self.company_name.nil?
      #create new company item 
      company = Company.new(name:self.company_name, is_active:true)
      company.save
      self.company_id = company.id
      
      Thread.new{ update_company(company.id, self.company_name) }
      
    elsif !self.company_id.nil?
      #set is_active field for this company, which means some users belongs to this company
      company = Company.find(self.company_id)
      if company.is_active == false
        company.is_active = true
        company.save
      end
      
    end
    
    def update_company(company_id, company_name)
      
      if LinkedinController.new.update_company(company_id, company_name)
        company = Company.find(company_id)
        company.is_verified = true
        company.save
      else
        # fail to supplement info for new company
      end 
    end
    
  end
    
    
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout 'application', except: :index
  #new company 
  def new 
    
  end
  
  #create a new company
  def create
    @company = Company.new(company_params)
    @company.save
    redirect_to @company
  end
  
  #show company info
  def show
    @company = Company.find(params[:id])
    @users = @company.users
  end
  
  #list all company
  def index
    @companies = Company.all
  end 
  
  #edit a company
  def edit
    @company = Company.find(params[:id])
  end
  
  #update a company
  def update
    @company = Company.find(params[:id])
 
    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end
 
  def destroy
    @company = Company.find(params[:id])
    @company.destroy
 
    redirect_to companies_path
  end
  
  private 
    def company_params
      params.require(:company).permit(:name, :description, :website, :logo)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/linkedin_helper.rb
module LinkedinHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/edit.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for :company, url: company_path(@company.id), method: :patch do |f| %>

 
    <%= f.label :name, "公司"%>
    <%= f.text_field :name %>
  
 
  
    <%= f.label :description, "关于"%>
    <%= f.text_area :description %>
  

  
    <%= f.label :website, "网址"%>
    <%= f.text_field :website %>
    
    <%= f.label :logo,  "上传Logo"%>
    <%= f.file_field :logo %>
  
   
  
    <%= f.submit class: "btn btn-large btn-primary"%>
  
<% end %>

<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<br />
<br />

<table class="table table-hover">
 
  <% @companies.each do |company| %>
  <tr><td>
  	<div class="container">
	 <div class="row-fluid">
      		<div class="span2"><%= image_tag company.logo.url %></div>
      		<div class="span10"><strong><%= link_to company.name, company_path(company) %></strong></br>
      				<%= company.industry.name_cn %>&nbsp;|&nbsp;
      				成立于<%= company.founded_year %>&nbsp;|&nbsp;<%= company.employee_count_range %>员工</br>
      				
      				<% if not company.tags.nil? %>
      					<% tags = company.tags.gsub('"', '').gsub('[', '').gsub(']', '')  %>
   					<% else %>
   						<% tags = company.industry.name %>
   					<% end %>
   					<span class="tags"><%= tags %></span></br>
   					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#company<%= company.id %>">
					关于</a>
		 <div id="company<%= company.id %>" class="collapse"><p><%= company.description %></p></div>
      		</div>  
    	</div>
    </div>
    
   
     
   
    </td></tr>

  <% end %>
</table>

app/views/companies/index__.html.erb
<% if current_user.try(:admin?) %>
<%= link_to '添加公司', new_company_path, class: "btn btn-primary" %>
<% end %>
<br />
<br />

<table class="table table-hover">
  <tr>
  	<th></th>
    <th>公司</th>
    <th>领域</th>
    <th>关于</th>
    <th>规模</th>
    <th>网址</th>
    <th></th>
    <th></th>
  </tr>
 
  <% @companies.each do |company| %>
    <tr>
      <td><%= image_tag company.logo.url(:medium) %></td>
      <td><%= link_to company.name, company_path(company) %></td>
      <td><%= company.industry.name %></td>
      
 	
      <td>
      	<button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#company<%= company.id %>">
			关于....
		</button>
		<div id="company<%= company.id %>" class="collapse"><%= company.description %></div>
      </td>
      
      
      
      <td><%= company.employee_count_range %></td>
      <td><%= company.website %></td>
      <% if current_user.try(:admin?) %>
      <td><%= link_to '编辑', edit_company_path(company) %></td>
 	  <td><%= link_to '删除', company_path(company), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/companies/new.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for :company, url: companies_path do |f| %>
  
    <%= f.label :name , "公司"%>
    <%= f.text_field :name %>
  
 
  
    <%= f.label :description , "关于"%>
    <%= f.text_area :description %>
  

  
    <%= f.label :website , "网址"%>
    <%= f.text_field :website %>
    
    <%= f.label :logo ,  "上传Logo"%>
    <%= f.file_field :logo %>
  
   
  <p>
    <%= f.submit "添加", class: "btn btn-large btn-primary"%>
  </p>
<% end %>

<%= link_to '公司列表', companies_path %>

</div>
</div>

app/views/companies/show.html.erb
<table class="table table-hover">
  <tr><td>
  	<div class="container">
	 <div class="row-fluid">
      		<div class="span2"><%= image_tag @company.logo.url %></div>
      		<div class="span10"><strong><%= @company.name %></strong></br>
      				<%= @company.industry.name_cn %></br>
      				<%= @company.founded_year %>年成立&nbsp;&nbsp;<%= @company.employee_count_range %>员工</br>
      				<%= link_to @company.website, @company.website,:target => '_blank' %>
      		</div>  
    	</div>
    </div>
    
    <div class="container">
    	<div class="row">
    		<div class="span2"></div>
    		<% tags = @company.tags.gsub('"', '').gsub('[', '').gsub(']', '') if not @company.tags.nil? %>
    		
    		
    		<div class="span10"><p class="tags"><span><%= tags %></span></p></div>
    	</div>
    </div>
    
    <div class="container">
    	<div class="row">
    	<div class="span2"></div>
    	<div class="span10">
		 <p><%= @company.description %></p>
      </div>
      </div>
     </div>
     
   
    </td></tr>
</table>


<br />
<br />
<br />
<br />

<table class="table table-hover">
 
  <% @users.each do |user| %>
  <tr><td>
  	<div class="container">
	 <div class="row-fluid">
      		<div class="span2"><%= image_tag user.avatar.url(:small) %></div>
      		<div class="span8"><strong><%= link_to user.name, user_path(user) %></strong></br>
      				部门:<%= user.dept %>&nbsp;&nbsp;职位:<%= user.position %></br>
      				<%= user.hometown.province %></br>
      				<%= user.china_school1.name %></br>
      				<%= user.us_school1.name %>
      		</div>  
      		<% if_connect = ConnectsController.if_connected(current_user.id, user.id) if not current_user.nil? %>
       		<% if !current_user.nil? && current_user.id == user.id %>
      			<div class="span2"></div>     		
      		<% elsif current_user.nil? || if_connect == 0%>
      			<div class="span2"><%= link_to "加为联系人", controller:"connects", action:"send_request", id:user.id %></div>
      		<% elsif if_connect == 1%>
      			<div class="span2"><%= link_to "联系请求已发送", "#" %></div>
      		<% else %>
      			<div class="span2"></br><br>
      		    <a href="#message_popup" role="button" class="btn" data-toggle="modal">留言</a></br></br>
      			<a href="#refer_request_popup<%=user.id%>"  role="button" class="btn" data-toggle="modal">请求Refer</a>
      			<%= render 'shared/refer_request_popup', :to => user %>
      			</div>
      		<% end %>
    	</div>
    </div>
   
    </td></tr>

  <% end %>
</table>