config/routes.rb
SeekRefer::Application.routes.draw do
  
  get 'autocomplete_company_name' => 'application#autocomplete_company_name'
  
  get "region_page/index"
  devise_for :users
  resources :companies
  resources :users
  resources :job_posts do
    get :autocomplete_position_name, :on => :collection
    get :autocomplete_company_name, :on => :collection
  end
  resources :follow_rules
  root 'homes#index'
  get 'homes' => 'homes#index'
  
  match '/signin',  to: 'devise/sessions#new',    via: 'get'
  
  get 'connects/send_request/:id' => 'connects#send_request'
  get 'connects/accept_request' => 'connects#accept_request'
  get 'connects/ignore_request' => 'connects#ignore_request'
  get 'connects/disconnect/:id' => 'connects#disconnect'
  post 'users/create' => 'users#create'
  get 'connects' => 'connects#index'

  
  get 'refer_requests/send_request' => 'refer_requests#send_request'
  post 'refer_requests/recv_request' => 'refer_requests#recv_request'
  get 'refer_request/view_profile' => 'refer_requests#view_profile'
  get 'refer_request/ignore_request' => 'refer_requests#ignore_request'
  get 'refer_request/upload_resume' => 'refer_requests#upload_resume'
  post 'refer_request/save_resume' => 'refer_requests#save_resume'
  post 'refer_request/refuse_request' => 'refer_requests#refuse_request'
  
  get 'refer_cases/show_referrer' => 'refer_cases#show_referrer'
  get 'refer_cases/show_referrer_old' => 'refer_cases#show_referrer_old'
  get 'refer_cases/show_referral' => 'refer_cases#show_referral'
  get 'refer_cases/show_referral_old' => 'refer_cases#show_referral_old'
  get 'refer_cases/create' => 'refer_cases#create'
  get 'refer_cases/edit' => 'refer_cases#edit'
  patch 'refer_cases/destroy' => 'refer_cases#destroy'
  patch 'refer_cases/update' => 'refer_cases#update'
  get 'refer_cases/feedback' => 'refer_cases#feedback'
  
  post 'refer_posts/create' => 'refer_posts#create'
  
  get 'linkedin/get_token' => 'linkedin#get_token'
  get 'linkedin/accept' => 'linkedin#accept'
  get 'linkedin/get_companies' => 'linkedin#get_companies'
  get 'linkedin/get_company' => 'linkedin#get_company'
  get 'linkedin/new' => 'linkedin#new'
  post 'linkedin/create' => 'linkedin#create'
  get 'linkedin/get_jobs_by_company' => 'linkedin#get_jobs_by_company'
 
 
  
 

  

end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  belongs_to :industry
  belongs_to :company
  belongs_to :location
  belongs_to :position
  belongs_to :poster, class_name: "User"
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_filter :authenticate_user!, except: ["index", "show"]
  autocomplete :position, :name
  autocomplete :company, :name
  
  def index
    @job_posts = JobPost.all
  end
  
  def new
    
  end
  
  def create
    @job_post = JobPost.new(job_post_params)
    @job_post.poster_id = current_user.id
    @job_post.save
    #send email to followers 
    Thread.new { notify_followers( @job_post ) }
    
    redirect_to job_posts_path    
  end
  
  def edit
    @job_post = JobPost.find(params[:id])
  end
  
  def show
    
    if params.has_key?("signedin") 
      authenticate_user!
    end
    @job_post = JobPost.find(params[:id])
  end
  
  def update
    @job_post = JobPost.find(params[:id])
 
    if @job_post.update(job_post_params)
      redirect_to @job_post
    else
      render 'edit'
    end
  end
  
  def destroy
    @job_post = JobPost.find(params[:id])
    @job_post.destroy
 
    redirect_to job_posts_path
  end
  
  private 
    def job_post_params
      params.require(:job_post).permit(:industry_id, :company_id, :location_id, :poster_id, :position, :content)
    end
  
    def notify_followers( post )
      @followers = User.where(id: FollowRule.select("follow_rules.follower_id").where("(company_id = ? OR company_id IS NULL) AND
                                                                                       (location_id = ? OR location_id IS NULL) AND
                                                                                       (industry_id = ? OR industry_id IS NULL) ",   post.company_id, post.location_id, post.industry_id))
      url = url_for(controller: "job_posts", action: "show", id: post.id, only_path: false)
      
      @followers.each do |follower|
        FollowMailer.notify_followers( follower, post, url).deliver 
      end
                                                                              
      
    end
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/edit.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for :job_post, url: job_post_path(@job_post.id), method: :patch do |f| %>

 
 	  <%= f.label :industry_id ,"领域"%>
 	  <%= f.select(:industry_id, Industry.all.map {|h| [h.name, h.id]},{:prompt => "选择领域"},{:class => 'selectpicker'}) %> 
  	  
  	  <%= f.label :location_id ,"地区"%>
 	  <%= f.select(:location_id, Location.all.map {|h| [h.name, h.id]},{:prompt => "选择地区"},{:class => 'selectpicker'}) %>
      
      <%= f.label :company_id ,"公司"%>
      <%= f.select(:company_id, Company.all.map {|h| [h.name, h.id]},{:prompt => "选择公司"},{:class => 'selectpicker'}) %>
 
 	  <%= f.label :position , "职位"%>
      <%= f.text_field :position %>
      
      <%= f.label :content , "详细描述"%>
      <%= f.text_area :content %>
  
   
  
    <%= f.submit "保存", class: "btn btn-large btn-primary"%>
  
<% end %>

app/views/job_posts/index.html.erb
<%= link_to '发布职位', new_job_post_path, class: "btn btn-primary" %>

<br />
<br />

<table class="table table-hover">
  <tr>
  	<th>领域</th>
    <th>公司</th>
    <th>地区</th>
    <th>职位</th>
    <th>发布者</th>
    <th></th>
    <th></th>
  </tr>
 
  <% @job_posts.each do |job_post| %>
    <tr>
      <td><%= job_post.industry.name %></td>
      <td><%= job_post.company.name %></td>
      <td><%= job_post.location.name %></td>
      <td><%= job_post.position %></td>
      <td><%= job_post.poster.name %></td>
      <td><%= link_to "详细", job_post_path(job_post) %></td>
      <% if user_signed_in? && ( current_user.try(:admin?) || current_user.id == job_post.poster_id ) %>
      <td><%= link_to '修改', edit_job_post_path(job_post) %></td>
 	  <td><%= link_to '删除', job_post_path(job_post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/job_posts/new.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for :job_post, url: job_posts_path do |f| %>
 	  
 	  <%= f.label :industry_id ,"领域"%>
 	  <%= f.select(:industry_id, Industry.all.map {|h| [h.name_cn, h.id]},{:prompt => "选择领域"},{:class => 'selectpicker'}) %> 
  	  
  	  <%= f.label :location_id ,"地区"%>
 	  <%= f.select(:location_id, Location.all.map {|h| [h.name, h.id]},{:prompt => "选择地区"},{:class => 'selectpicker'}) %>
      
 	  <%= f.label :company_id , "公司"%>
      <%= f.autocomplete_field :company_name, autocomplete_company_name_job_posts_path, :id_element=>"#job_post_company_id" %>
      <%= f.hidden_field :company_id %>
      
 	  <%= f.label :position , "职位"%>
      <%= f.autocomplete_field :position_name, autocomplete_position_name_job_posts_path, :id_element=>"#job_post_position_id" %>
      <%= f.hidden_field :position_id %>
      
      <%= f.label :content , "详细描述"%>
      <%= f.text_area :content %>
      
  <p>
    <%= f.submit "发布", class: "btn btn-large btn-primary"%>
  </p>
<% end %>



</div>
</div>

app/views/job_posts/show.html.erb
<script type="text/javascript">


jQuery(document).ready(function($) {
  $('a[rel*=facebox]').facebox()
  $('#facebox .body').width('1000px');
})

</script>


<table class="table table-hover">
  <tr>
  	
  </tr>
 
	<tr>
	 <td>
  		<strong>领域 </strong>
  		<%= @job_post.industry.name %>
	 </td>
	</tr>

	<tr>
	 <td>
  		<strong>公司 </strong>
  		<%= @job_post.company.name %>
	 </td>
	</tr>
	
	<tr>
	 <td>
  		<strong>地点 </strong>
  		<%= @job_post.location.name %>
	 </td>
	</tr>
	<tr>
	 <td>
  		<strong>职位 </strong>
  		<%= @job_post.position %>
	 </td>
	</tr>
	<tr>
	 <td>
  		<p4><pre><%= @job_post.content %></pre></p4>
	 </td>
	</tr>
	<tr>
	 <td>
  		<strong>发布者 </strong>
  		<%= @job_post.poster.name %>
	 </td>
	</tr>
	<tr>
	 <td>
	 	<% if user_signed_in? %>
	 		<%= link_to '求推荐', {controller:"refer_requests", action:"send_request", id:@job_post.poster.id}, :rel => "facebox" %>
	 	<% else%>
	 	    <%= link_to '求推荐', {action:"show", id:@job_post.id, signedin: true} %>
	 	<% end %>
	 </td>
	</tr>


</table>